import React from "react";
import { Button, Modal, ModalHeader, ModalBody, ModalFooter } from 'reactstrap';
import "bootstrap/dist/css/bootstrap.min.css";
import "font-awesome/css/font-awesome.min.css";

export class ModalHelp extends React.Component {

	constructor(props) {
	  super(props);
	  this.state = {
			modalHelp:false
	  };
	}

	handleInputChange = (event) => {
    const target = event.target;
    const value = target.type === 'checkbox' ? target.checked : target.value;
    const name = target.name;

    this.setState({
      [name]: value
    });
  }



  loadData = (data) => {
    var v = [];
    var i;
    for (i = 0; i < data[0].length; i+=2) {
      if(i===0){
        v.push([data[0][i],data[0][i+1]])
      }else{
        v.push([parseInt(data[0][i]),parseInt(data[0][i+1])])
      }
    }
    this.props.setData(v)
  }

  render() {
    return (
      <div>
        <Modal isOpen={this.props.modalHelp} toggle={this.props.toggle} className={this.props.className}>
          <ModalHeader toggle={this.props.toggle}>Help</ModalHeader>
          <ModalBody>
            <div className="container">
              <h5 className="pt-4">Add data</h5>
              <p>
								In this panel you can add and edit your data. In order to edit data you have to click one input inside table and
								type or paste number. Not number values are not accepted.
							</p>
							<br/>
							<p>
								You can here also edit rows and columns description. You can do this by inserting text inside table row or column headers.
								Default column description is "y0, y1, ..." and row description "x0, x1, ...".
							</p>
							<br/>
							<p>
								Next option is column color edition. In order to edit column values color, you need to click special inser button
								in "Color" row, and select color. Default color is black (#000000).
							</p>
							<input type="color" className="form-control"/>
							<br/>
							<p>
								Button "Delete all", allows us to delete all data from table (all rows and columns).
							</p>
							<button type="button" className="btn btn-warning mb-2" style={{color:"#ffffff"}}><i className="fas fa-trash-alt"></i> Delete all</button>
							<br/>
							<p>
								In this panel you can also add rows and columns to table. In order to add column you need to click button
								"Add column" and in order to add row you need to click button "Add row".
							</p>
							<button type="button" className="btn btn-outline-primary"><i className="fas fa-plus"></i> Add row</button>
							<button type="button" className="btn btn-outline-primary ml-4"><i className="fas fa-plus"></i> Add column</button>

              <h5 className="pt-4">Undo</h5>
              <p>This buttow allows us to undo previous operations.</p>

              <h5 className="pt-4">Import data</h5>
              <p>
                This option allow us to import data to our program. There are available two ways to import data:
							</p>
							<ul>
 								<li> from * .csv file (it is advisable to use only files generated by app) </li>
								<li> from firebase </li>
              </ul>
							<p>
								In panel showing after selecting firebase as a source, you can select chart data which you want to import, by
								clicking button "Import". You can here also delete chart data by clicking "Delete" button. If you want to add
								to firebase new chart data, you can do this in panel showing after clicking "Export data".
							</p>
							<strong>WARNING: After import your current data will be replaced by new data</strong>

              <h5 className="pt-4">Export data</h5>
              <p>
								This option allow us to export data. There are available two ways to export data:
							</p>
							<ul>
 								<li>
									* .csv file (name of file is "react_chart_app_data.csv")
								</li>
								<li>
									to firebase (if you want to export data to firebase you have to set chart name before in "Settings" panel)
								</li>
              </ul>

              <h5 className="pt-4">Settings</h5>
              <p>
                This panel allows you to:
              </p>
							<ul>
 								<li>
									set chart name
								</li>
								<li>
									set x-axis tittle
								</li>
								<li>
									set y-axis tittle
								</li>
								<li>
									show/hide legend
								</li>
								<li>
									select chart type
								</li>
              </ul>

              <h5 className="pt-4">Help</h5>
              <p>
                This option shows help.
              </p>
            </div>
          </ModalBody>
          <ModalFooter>
            <Button color="secondary" onClick={this.props.toggle}>Cancel</Button>
          </ModalFooter>
        </Modal>
      </div>
    );
  }
}
